image:
  file: .gitpod.Dockerfile

tasks:
- name: Start Couchbase
  command:  ./startcb.sh
- name: Log use
  command: curl -s 'https://da-demo-images.s3.amazonaws.com/runItNow_outline.png?couchbase-example=java-springdata-quickstart-repo&source=gitpod' > /dev/null
- name: Start app
  command: ./gradlew bootRun
# exposed ports
ports:
- port: 8080
  onOpen: open-preview
- port: 8091
  onOpen: open-browser
- port: 8092-10000
  onOpen: ignore
- port: 4369
  onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true

vscode:
  extensions:
    - redhat.java
    - vscjava
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
